name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  verify-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check code using Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Check code formatting
        run: bun run format:check

      - name: Build code
        run: bun build.ts

  build-and-deploy:
    needs: verify-code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          echo "$SSH_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $GCE_USERNAME@$PUBLIC_IP "          
          cd church_finance_api          

          git fetch origin
          git reset --hard origin/main
          git pull

          rm -rf node_modules
          rm -rf dist

          ~/.bun/bin/bun install --frozen-lockfile
          sudo systemctl restart church_api.service

          "

    env:
      SSH_KEY: ${{ secrets.GCP_SSH_KEY }}
      PUBLIC_IP: ${{ secrets.GCP_PUBLIC_IP }}
      GCE_USERNAME: ${{ secrets.GCP_USERNAME }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
